"use client";

import { motion } from "framer-motion";
import { ExplanationPanel } from "@/components/experience/ExplanationPanel";
import { QuizPanel } from "@/components/experience/QuizPanel";
import { MissionCard } from "@/components/experience/MissionCard";
import { InsightsPanel } from "@/components/insights/InsightsPanel";
import { PageTransition } from "@/components/shared/PageTransition";
import { Progress } from "@/components/ui/progress";
import type { ExperiencePayload } from "@/lib/types";

interface LessonShellProps {
  payload: ExperiencePayload;
}

export function LessonShell({ payload }: LessonShellProps) {
  if (!payload || payload.templateId !== "ai_lesson") {
    return (
      <PageTransition className="mx-auto flex min-h-screen w-full max-w-6xl flex-col items-center justify-center px-4 py-6">
        <div className="text-center">
          <p className="text-muted-foreground">Invalid lesson payload.</p>
        </div>
      </PageTransition>
    );
  }

  const lesson = payload.lesson;
  const title = lesson?.title || payload.topic || "STEM Lesson";
  const summary = lesson?.summary || "";

  const keyConcepts = Array.isArray(lesson?.keyConcepts) ? lesson.keyConcepts : [];
  const visualCards = Array.isArray(lesson?.visualCards) ? lesson.visualCards : [];

  const quizQuestions = Array.isArray(payload.quiz?.questions) ? payload.quiz.questions : [];

  const lessonSummary = summary || "A tailored lesson that includes a clear explanation, visual thinking cards, and a practice quiz to help you master this topic.";
  const stats = [
    { label: "Concept cards", value: visualCards.length },
    { label: "Core ideas", value: keyConcepts.length },
    { label: "Quiz questions", value: quizQuestions.length },
  ];

  return (
    <PageTransition className="mx-auto flex min-h-screen w-full max-w-6xl flex-col gap-6 px-4 py-6 sm:py-8">
      <section className="rounded-[2rem] border border-white/10 bg-slate-950/80 p-6 shadow-2xl ring-1 ring-white/5 backdrop-blur-xl">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between">
          <div className="space-y-4">
            <span className="inline-flex rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-sm font-semibold text-primary">
              AI Lesson
            </span>
            <div className="space-y-3">
              <h1 className="text-3xl font-semibold tracking-tight sm:text-4xl">{title}</h1>
              <p className="max-w-2xl text-sm leading-7 text-muted-foreground">{lessonSummary}</p>
            </div>
          </div>

          <div className="grid gap-3 sm:grid-cols-3">
            {stats.map((stat) => (
              <div
                key={stat.label}
                className="rounded-3xl border border-white/10 bg-background/80 p-4 text-center shadow-sm"
              >
                <p className="text-3xl font-semibold text-foreground">{stat.value}</p>
                <p className="text-xs uppercase tracking-[0.24em] text-muted-foreground">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-6 grid gap-4 lg:grid-cols-[1.5fr_0.85fr]">
          <div className="rounded-3xl border border-white/10 bg-background/90 p-5 shadow-sm">
            <p className="text-sm font-medium text-primary">What you’ll learn</p>
            <p className="mt-2 text-sm leading-7 text-muted-foreground">
              Explore the lesson in a structured flow with focused concepts and visuals designed for fast judgment and retention.
            </p>
          </div>

          <div className="rounded-3xl border border-white/10 bg-background/90 p-5 shadow-sm">
            <div className="flex items-center justify-between gap-4">
              <div>
                <p className="text-sm font-medium text-foreground">Lesson readiness</p>
                <p className="text-xs text-muted-foreground">Generated by AI and ready to review.</p>
              </div>
              <span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">
                Live
              </span>
            </div>
            <div className="mt-4">
              <Progress value={100} />
            </div>
          </div>
        </div>
      </section>

      <div className="grid gap-6 lg:grid-cols-5">
        <div className="lg:col-span-3 space-y-4">
          <motion.div
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35 }}
          >
            <ExplanationPanel explanation={payload.explanation} />
          </motion.div>

          {keyConcepts.length > 0 && (
            <section>
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                Key Concepts
              </h2>
              <div className="grid gap-4 sm:grid-cols-2">
                {keyConcepts.map((k, i) => (
                  <div key={i} className="rounded-3xl border border-white/10 bg-background/90 p-5 shadow-sm">
                    <h3 className="text-sm font-semibold text-foreground">{k.title}</h3>
                    {k.detail && <p className="mt-2 text-sm leading-6 text-muted-foreground">{k.detail}</p>}
                  </div>
                ))}
              </div>
            </section>
          )}

          {visualCards.length > 0 && (
            <section>
              <h2 className="mb-4 text-sm font-semibold uppercase tracking-[0.2em] text-muted-foreground">
                Visual Learning Cards
              </h2>
              <div className="grid gap-4 sm:grid-cols-2">
                {visualCards.map((c, i) => (
                  <div key={i} className="rounded-3xl border border-white/10 bg-slate-900/80 p-5 shadow-sm">
                    <h3 className="text-sm font-semibold text-foreground">{c.title}</h3>
                    {c.caption && <p className="mt-2 text-sm leading-6 text-muted-foreground">{c.caption}</p>}
                  </div>
                ))}
              </div>
            </section>
          )}
        </div>

        <aside className="lg:col-span-2 space-y-4">
          <div className="lg:sticky lg:top-20 space-y-4">
            <MissionCard title={title} objective={summary} />
            {quizQuestions.length > 0 && <QuizPanel questions={quizQuestions} />}
            <InsightsPanel topicKey={payload.topic} />
          </div>
        </aside>
      </div>
    </PageTransition>
  );
}
